# Generated by O3DE install

set_property(TARGET BookProject.GameLauncher
    APPEND_STRING PROPERTY IMPORTED_LOCATION
        $<$<CONFIG:profile>:${LY_ROOT_FOLDER}/bin/Windows/profile/Default/./BookProject.GameLauncher.exe>
)
set_property(TARGET BookProject.GameLauncher
    PROPERTY IMPORTED_LOCATION_PROFILE
        ${LY_ROOT_FOLDER}/bin/Windows/profile/Default/./BookProject.GameLauncher.exe
)
