# Generated by O3DE install

set_property(TARGET BookProject.UnifiedLauncher
    APPEND_STRING PROPERTY IMPORTED_LOCATION
        $<$<CONFIG:profile>:${LY_ROOT_FOLDER}/bin/Windows/profile/Default/./BookProject.UnifiedLauncher.exe>
)
set_property(TARGET BookProject.UnifiedLauncher
    PROPERTY IMPORTED_LOCATION_PROFILE
        ${LY_ROOT_FOLDER}/bin/Windows/profile/Default/./BookProject.UnifiedLauncher.exe
)
