#
# Copyright (c) Contributors to the Open 3D Engine Project.
# For complete copyright and license terms please see the LICENSE at the root of this distribution.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT
#
#

# Generated by O3DE

ly_add_target(
    NAME BookProject.GameLauncher IMPORTED EXECUTABLE
    NAMESPACE AZ
    COMPILE_DEFINITIONS
        INTERFACE

    INCLUDE_DIRECTORIES
        INTERFACE
            
    BUILD_DEPENDENCIES
        INTERFACE

    RUNTIME_DEPENDENCIES
        AZ::Launcher.Static
        AZ::Launcher.Game.Static
        AWSCore.Clients
        Achievements.Clients
        Atom.Clients
        AtomViewportDisplayInfo.Clients
        Atom_Bootstrap.Clients
        AudioSystem.Clients
        BookProject.Clients
        Camera.Clients
        CameraFramework.Clients
        CommonFeaturesAtom.Clients
        Compression.Clients
        DebugDraw.Clients
        DiffuseProbeGrid.Clients
        EMotionFX.Clients
        GameState.Clients
        ImGui.Clients
        Legacy::CrySystem
        LyShine.Clients
        LyShineExamples.Clients
        Maestro.Clients
        MyGem.Clients
        NvCloth.Clients
        PhysX.Clients
        SaveData.Clients
        ScriptCanvasPhysics.Clients
        ScriptEvents.Clients
        StartingPointInput.Clients
        TextureAtlas.Clients
        WhiteBox.Clients
    TARGET_PROPERTIES
        LY_PROJECT_NAME BookProject
)



set(configs profile)
foreach(config ${configs})
    include("Platform/Windows/Default/BookProject.GameLauncher_${config}.cmake" OPTIONAL)
endforeach()

# Generated by O3DE

ly_add_target(
    NAME BookProject.ServerLauncher IMPORTED EXECUTABLE
    NAMESPACE AZ
    COMPILE_DEFINITIONS
        INTERFACE

    INCLUDE_DIRECTORIES
        INTERFACE
            
    BUILD_DEPENDENCIES
        INTERFACE

    RUNTIME_DEPENDENCIES
        AZ::Launcher.Static
        AZ::Launcher.Server.Static
        AWSCore.Servers
        Atom.Servers
        AtomViewportDisplayInfo.Servers
        Atom_Bootstrap.Servers
        BookProject.Servers
        Camera.Servers
        CameraFramework.Servers
        CommonFeaturesAtom.Servers
        Compression.Servers
        DiffuseProbeGrid.Servers
        EMotionFX.Servers
        GameState.Servers
        ImGui.Servers
        Legacy::CrySystem
        LyShine.Servers
        LyShineExamples.Servers
        Maestro.Servers
        MyGem.Servers
        NvCloth.Servers
        PhysX.Servers
        ScriptCanvasPhysics.Servers
        ScriptEvents.Servers
        StartingPointInput.Servers
        TextureAtlas.Servers
        WhiteBox.Servers
    TARGET_PROPERTIES
        LY_PROJECT_NAME BookProject
)



set(configs profile)
foreach(config ${configs})
    include("Platform/Windows/Default/BookProject.ServerLauncher_${config}.cmake" OPTIONAL)
endforeach()

# Generated by O3DE

ly_add_target(
    NAME BookProject.UnifiedLauncher IMPORTED EXECUTABLE
    NAMESPACE AZ
    COMPILE_DEFINITIONS
        INTERFACE

    INCLUDE_DIRECTORIES
        INTERFACE
            
    BUILD_DEPENDENCIES
        INTERFACE

    RUNTIME_DEPENDENCIES
        AZ::Launcher.Static
        AZ::Launcher.Unified.Static
        AWSCore.Unified
        Atom.Unified
        AtomViewportDisplayInfo.Unified
        Atom_Bootstrap.Unified
        AudioSystem.Unified
        BookProject.Unified
        Camera.Unified
        CameraFramework.Unified
        CommonFeaturesAtom.Unified
        Compression.Unified
        DebugDraw.Unified
        DiffuseProbeGrid.Unified
        EMotionFX.Unified
        GameState.Unified
        ImGui.Unified
        Legacy::CrySystem
        LyShine.Unified
        LyShineExamples.Unified
        Maestro.Unified
        MyGem.Unified
        NvCloth.Unified
        PhysX.Unified
        ScriptCanvasPhysics.Unified
        ScriptEvents.Unified
        StartingPointInput.Unified
        TextureAtlas.Unified
        WhiteBox.Unified
    TARGET_PROPERTIES
        LY_PROJECT_NAME BookProject
)



set(configs profile)
foreach(config ${configs})
    include("Platform/Windows/Default/BookProject.UnifiedLauncher_${config}.cmake" OPTIONAL)
endforeach()

ly_set_gem_variant_to_load(TARGETS BookProject.GameLauncher VARIANTS Clients)
ly_set_gem_variant_to_load(TARGETS BookProject.ServerLauncher VARIANTS Servers)
ly_set_gem_variant_to_load(TARGETS BookProject.UnifiedLauncher VARIANTS Unified)
ly_enable_gems(GEMS Atom_Bootstrap AtomShader AtomViewportDisplayInfo Camera CommonFeaturesAtom EditorModeFeedback Maestro PrefabBuilder SceneProcessing)
ly_enable_gems(PROJECT_NAME BookProject GEMS AWSCore Achievements Atom AudioSystem BookProject CameraFramework Compression DebugDraw DiffuseProbeGrid EMotionFX EditorPythonBindings GameState ImGui LandscapeCanvas LyShine LyShineExamples UiBasics MyGem NvCloth PhysX PrefabBuilder PrimitiveAssets SaveData ScriptCanvasPhysics ScriptEvents StartingPointInput TextureAtlas WhiteBox)
